# Project: Cards
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe -D__DEBUG__
CC       = gcc.exe -D__DEBUG__
WINDRES  = windres.exe
OBJ      = card.o clean.o deck.o hand.o studentnumber-lbyec2b-activity4-labrepalt.o test.o
LINKOBJ  = card.o clean.o deck.o hand.o studentnumber-lbyec2b-activity4-labrepalt.o test.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc -g3
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 11816600-lbyec2b-activity4-labrepalt.exe
CXXFLAGS = $(CXXINCS) -g3
CFLAGS   = $(INCS) -g3
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

card.o: card.c
	$(CPP) -c card.c -o card.o $(CXXFLAGS)

clean.o: clean.c
	$(CPP) -c clean.c -o clean.o $(CXXFLAGS)

deck.o: deck.c
	$(CPP) -c deck.c -o deck.o $(CXXFLAGS)

hand.o: hand.c
	$(CPP) -c hand.c -o hand.o $(CXXFLAGS)

studentnumber-lbyec2b-activity4-labrepalt.o: studentnumber-lbyec2b-activity4-labrepalt.cpp
	$(CPP) -c studentnumber-lbyec2b-activity4-labrepalt.cpp -o studentnumber-lbyec2b-activity4-labrepalt.o $(CXXFLAGS)

test.o: test.c
	$(CPP) -c test.c -o test.o $(CXXFLAGS)
